name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, x86, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: dotnet build FriendlyPaletteGenerator/FriendlyPaletteGenerator.csproj --configuration Release -r win-${{ matrix.architecture }} --self-contained false
